### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by kannangce**

### CODE REVIEW

**Comment by tonsky** [comment]
Thanks! I think `-M` got there by a mistake:

```
[~/ws/skija/examples/clojure] clj -J-XstartOnFirstThread -M -m  lwjgl.main
Missing required argument for "-M ALIASES"
```

**Comment by kannangce** [comment]
It worked for me. When I don't use `-M`, I get this warning,
image

**Comment by kannangce** [comment]
Removed `-M` though

**Comment by tonsky** [comment]
Sorry, I just updated clojure and it is now mandatory. I wish `clj` tool adopt as strong backwards compatibility as Clojure itself. The fact that `clj` version is not visible anywhere only makes things worse

**Comment by tonsky** [comment]
Merged your first version, sorry for the confusion.

**Pull request closed without merging**
